#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/BatakDual.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/gst1-java-core-1.2.0.jar:$APPDIR/lib/video.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/mp3spi1.9.5.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/jsminim.jar" BatakDual "$@"
